import type { Finding, Report, ToolRec } from "./types";

/** Emits a drop-in module that registers the recommended tools with document.modelContext. */
export function generateCode(origin: string, tools: ToolRec[]): string {
  const lines: string[] = [];
  lines.push(`// webmcp-tools.js — generated by Overturn Retrofit for ${origin}`);
  lines.push(`// Drop this module into the top-level page (not an iframe). Serve with headers:`);
  lines.push(`//   Origin-Agent-Cluster: ?1`);
  lines.push(`//   Permissions-Policy: tools=(self)`);
  lines.push(`// Reads carry readOnlyHint. Write tools return a proposal the page renders.`);
  lines.push(`// Gated tools return pending_confirmation — only the user's click on your confirm UI may commit.`);
  lines.push(``);
  lines.push(`const mc = document.modelContext ?? navigator.modelContext;`);
  lines.push(`const controllers = new Map();`);
  lines.push(``);
  lines.push(`async function register(tool) {`);
  lines.push(`  controllers.get(tool.name)?.abort();`);
  lines.push(`  const c = new AbortController();`);
  lines.push(`  controllers.set(tool.name, c);`);
  lines.push(`  await mc.registerTool(tool, { signal: c.signal });`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`// TODO: wire these to your app's data and actions. Keep outputs under ~1.5K characters.`);
  lines.push(`const app = {`);
  lines.push(`  read: async (name, input) => ({ todo: \`return structured data for \${name}\`, input }),`);
  lines.push(`  propose: async (name, input) => ({ status: "proposed", rendered: "on page", input }),`);
  lines.push(`  gate: async (name, input) => ({ status: "pending_confirmation", message: "Confirm card shown; the user's click commits.", input }),`);
  lines.push(`};`);
  lines.push(``);
  lines.push(`export async function registerWebMCPTools() {`);
  lines.push(`  if (!mc || typeof mc.registerTool !== "function") return; // browser without WebMCP: page keeps working`);
  for (const t of tools) {
    const exec = t.kind === "read" ? "app.read" : t.kind === "write" ? "app.propose" : "app.gate";
    lines.push(`  await register({`);
    lines.push(`    name: ${JSON.stringify(t.name)},`);
    lines.push(`    description: ${JSON.stringify(t.description)},`);
    lines.push(`    inputSchema: ${JSON.stringify(t.inputSchema)},`);
    lines.push(`    annotations: { readOnlyHint: ${t.kind === "read"} },`);
    lines.push(`    execute: (input) => ${exec}(${JSON.stringify(t.name)}, input),`);
    lines.push(`  });`);
  }
  lines.push(`}`);
  lines.push(``);
  lines.push(`registerWebMCPTools();`);
  return lines.join("\n");
}

const sevLabel: Record<Finding["severity"], string> = { blocker: "Blocker", gap: "Gap", note: "Note" };

export function generateMarkdown(r: Omit<Report, "markdown">): string {
  const out: string[] = [];
  out.push(`# Agent-readiness report — ${r.origin}`);
  out.push(``);
  out.push(`Scanned ${r.scannedAt} (${r.mode}) · ${r.summary.pagesScanned} pages · score **${r.score.value}/100 (${r.score.grade})** — ${r.score.label}`);
  out.push(``);
  out.push(`| | |`);
  out.push(`|---|---|`);
  out.push(`| Forms | ${r.summary.forms} |`);
  out.push(`| Tables / lists | ${r.summary.tables} |`);
  out.push(`| Documents (PDF) | ${r.summary.pdfs} |`);
  out.push(`| Offline channels (fax/mail/phone-only) | ${r.summary.offlineChannels} |`);
  out.push(`| Existing WebMCP | ${r.summary.existingWebMCP ? "yes" : "no"} |`);
  out.push(`| WebMCP headers | ${r.summary.headersOk ? "present" : "missing"} |`);
  out.push(``);
  out.push(`## Findings`);
  for (const f of r.findings) {
    out.push(``);
    out.push(`### ${sevLabel[f.severity]} — ${f.title}`);
    out.push(f.detail);
    out.push(``);
    out.push(`**Fix:** ${f.fix}`);
    for (const e of f.evidence.slice(0, 3)) out.push(`- ${e.page} — "${e.snippet}"`);
  }
  out.push(``);
  out.push(`## Recommended tools`);
  out.push(``);
  out.push(`| Tool | Kind | Why |`);
  out.push(`|---|---|---|`);
  for (const t of r.tools) out.push(`| \`${t.name}\` | ${t.kind} | ${t.why} |`);
  out.push(``);
  out.push(`## Design rules`);
  out.push(`- Reads are free (\`readOnlyHint\`); writes return proposals the page renders; gated writes return \`pending_confirmation\` and only the user's click commits.`);
  out.push(`- Register on the top-level page; scope tools to the page/state the user is on; descriptions ≤ 500 chars; outputs ≤ 1.5K chars.`);
  out.push(`- Tools run in the user's signed-in session — no new OAuth.`);
  return out.join("\n");
}
